In [1]:
import pandas as pd

In [5]:
# spojení excelů 

aus1 = pd.read_csv('datasets/austria-bundesliga-players-2026-to-2027-stats.csv')
aus2 = pd.read_csv('datasets/austria-2-liga-players-2026-to-2027-stats.csv')
bos1 = pd.read_csv('datasets/bosnia-and-herzegovina-premier-league-of-bosnia-players-2026-to-2027-stats.csv')
bul1 = pd.read_csv('datasets/bulgaria-first-league-players-2026-to-2027-stats.csv')
cro1 = pd.read_csv('datasets/croatia-prva-hnl-players-2026-to-2027-stats.csv')
cze1 = pd.read_csv('datasets/czech-republic-first-league-players-2026-to-2027-stats.csv')
den1 = pd.read_csv('datasets/denmark-superliga-players-2026-to-2027-stats.csv')
den2 = pd.read_csv('datasets/denmark-1st-division-players-2026-to-2027-stats.csv')
est1 = pd.read_csv('datasets/estonia-meistriliiga-players-2026-to-2026-stats.csv')
fin1 = pd.read_csv('datasets/finland-veikkausliiga-players-2026-to-2026-stats.csv')
hun1 = pd.read_csv('datasets/hungary-nb-i-players-2026-to-2027-stats.csv')
lat1 = pd.read_csv('datasets/latvia-virsliga-players-2026-to-2026-stats.csv')
nor1 = pd.read_csv('datasets/norway-eliteserien-players-2026-to-2026-stats.csv')
nor2 = pd.read_csv('datasets/norway-first-division-players-2026-to-2026-stats.csv')
pol1 = pd.read_csv('datasets/poland-ekstraklasa-players-2026-to-2027-stats.csv')
pol2 = pd.read_csv('datasets/poland-1-liga-players-2026-to-2027-stats.csv')
rom1 = pd.read_csv('datasets/romania-liga-i-players-2026-to-2027-stats.csv')
ser1 = pd.read_csv('datasets/serbia-superliga-players-2026-to-2027-stats.csv')
ser2 = pd.read_csv('datasets/serbia-prva-liga-players-2026-to-2027-stats.csv')
svk1 = pd.read_csv('datasets/slovakia-super-liga-players-2026-to-2027-stats.csv')
slo1 = pd.read_csv('datasets/slovenia-prvaliga-players-2026-to-2027-stats.csv')
swe1 = pd.read_csv('datasets/sweden-allsvenskan-players-2026-to-2026-stats.csv')
swe2 = pd.read_csv('datasets/sweden-superettan-players-2026-to-2026-stats.csv')
swi1 = pd.read_csv('datasets/switzerland-super-league-players-2026-to-2027-stats.csv')
ukr1 = pd.read_csv('datasets/ukraine-ukrainian-premier-league-players-2026-to-2027-stats.csv')

In [6]:
# přidání sloupce s národností ligy

aus1[['league_name', 'league_nationality']] = ['Austrian Bundesliga', 'Austria']
aus2[['league_name', 'league_nationality']] = ['Austrian 2. Liga', 'Austria']
bos1[['league_name', 'league_nationality']] = ['Bosnian WWIN Liga BiH', 'Bosnia and Herzegovina']
bul1[['league_name', 'league_nationality']] = ['Bulgarian Parva Liga', 'Bulgaria']
cro1[['league_name', 'league_nationality']] = ['Croatian HNL', 'Croatia']
cze1[['league_name', 'league_nationality']] = ['Czech Chance Liga', 'Czechia']
den1[['league_name', 'league_nationality']] = ['Danish Superliga', 'Denmark']
den2[['league_name', 'league_nationality']] = ['Danish Betinia Liga', 'Denmark']
est1[['league_name', 'league_nationality']] = ['Estonian Premium Liiga', 'Estonia']
fin1[['league_name', 'league_nationality']] = ['Finland Veikkausliiga', 'Finland']
hun1[['league_name', 'league_nationality']] = ['Hungarian Fizz Liga', 'Hungary']
lat1[['league_name', 'league_nationality']] = ['Latvian Virsliga', 'Latvia']
nor1[['league_name', 'league_nationality']] = ['Eliteserien', 'Norway']
nor2[['league_name', 'league_nationality']] = ['Norway First Division', 'Norway']
pol1[['league_name', 'league_nationality']] = ['Polish Ekstraklasa', 'Poland']
pol2[['league_name', 'league_nationality']] = ['Polish Betclic 1. Liga', 'Poland']
rom1[['league_name', 'league_nationality']] = ['Romanian SuperLiga', 'Romania']
ser1[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Superliga', 'Serbia']
ser2[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Prva Liga', 'Serbia']
svk1[['league_name', 'league_nationality']] = ['Slovak Niké Liga', 'Slovakia']
slo1[['league_name', 'league_nationality']] = ['Slovenian PrvaLiga', 'Slovenia']
swe1[['league_name', 'league_nationality']] = ['Sweden Allsvenskan', 'Sweden']
swe2[['league_name', 'league_nationality']] = ['Sweden Superettan', 'Sweden']
swi1[['league_name', 'league_nationality']] = ['Swiss Super League', 'Switzerland']
ukr1[['league_name', 'league_nationality']] = ['Ukraine Premier League', 'Ukraine']

In [7]:
# spojení do databáze

datasets = [aus1, aus2, bos1, bul1, cro1, cze1, den1, den2, est1, fin1, pol1, pol2, hun1, lat1, nor1, nor2, rom1, ser1, ser2, svk1, slo1, swe1, swe2, swi1, ukr1]
df = pd.concat(datasets, ignore_index=True)

In [8]:
# filtr a změna pořadí požadovaných sloupců

cols = ['full_name', 'birthday_GMT', 'age', 'nationality', 'position', 'Current Club', 'league_name', 'league_nationality', 'season', 'appearances_overall', 'minutes_played_overall', 'goals_overall', 'goals_per_90_overall', 
        'min_per_goal_overall', 'xg_total_overall', 'xg_per_90_overall', 'npxg_total_overall', 'npxg_per_90_overall', 'assists_overall', 'assists_per_90_overall', 'min_per_assist_overall', 
        'xa_total_overall', 'xa_per_90_overall', 'goals_involved_per_90_overall', 'average_rating_overall', 'rank_in_league_top_defenders', 'rank_in_league_top_midfielders', 'rank_in_league_top_attackers', 
        'shots_total_overall', 'shots_per_90_overall', 'shots_on_target_total_overall', 'shots_on_target_per_90_overall', 'shot_accuraccy_percentage_overall', 'passes_total_overall', 'passes_per_90_overall', 
        'passes_completed_total_overall', 'passes_completed_per_90_overall', 'pass_completion_rate_overall', 'key_passes_total_overall', 'key_passes_per_90_overall', 'crosses_total_overall', 
        'crosses_per_90_overall', 'accurate_crosses_total_overall', 'accurate_crosses_per_90_overall', 'cross_completion_rate_overall',  'dribbles_total_overall', 'dribbles_per_90_overall', 
        'dribbles_successful_total_overall', 'dribbles_successful_per_90_overall', 'dribbled_past_total_overall', 'dribbled_past_per_90_overall', 'tackles_total_overall', 'tackles_per_90_overall', 
        'interceptions_total_overall', 'interceptions_per_90_overall', 'blocks_total_overall', 'blocks_per_90_overall', 'clearances_total_overall', 'clearances_per_90_overall', 'aerial_duels_won_total_overall', 
        'aerial_duels_won_per_90_overall', 'duels_total_overall', 'duels_per_90_overall', 'duels_won_total_overall', 'duels_won_per_90_overall', 'clean_sheets_overall', 'conceded_overall', 
        'conceded_per_90_overall', 'saves_total_overall', 'saves_per_90_overall', 'shots_faced_total_overall', 'shots_faced_per_90_overall', 'save_percentage_overall', 'punches_total_overall', 
        'punches_per_90_overall', 'pens_saved_total_overall'
]

df = df[cols]
df

,full_name,birthday_GMT,age,nationality,position,Current Club,league_name,league_nationality,season,appearances_overall,...,conceded_overall,conceded_per_90_overall,saves_total_overall,saves_per_90_overall,shots_faced_total_overall,shots_faced_per_90_overall,save_percentage_overall,punches_total_overall,punches_per_90_overall,pens_saved_total_overall
0,NaN,1989/07/08,37,China,Midfielder,Austria Lustenau,Austrian Bundesliga,Austria,2026/2027,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aaron Sky Schwarz,2004/03/20,22,Austria,Forward,Wolfsberger AC,Austrian Bundesliga,Austria,2026/2027,5,...,3,0.99,0.0,0.0,3.0,0.99,0.0,0.0,0.0,0.0
2,Abdoulaye Kanté,2005/05/15,21,Ivory Coast,Forward,Austria Wien,Austrian Bundesliga,Austria,2026/2027,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abobkar Bari,2000/07/02,26,Gambia,Midfielder,Salzburg,Austrian Bundesliga,Austria,2026/2027,6,...,4,0.76,0.0,0.0,4.0,0.76,0.0,0.0,0.0,0.0
4,Aboubacar Sidiki Camara,2006/09/30,19,Burkina Faso,Forward,Salzburg,Austrian Bundesliga,Austria,2026/2027,4,...,1,0.56,0.0,0.0,1.0,0.56,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10477,Yevhenii Pastukh,2004/03/19,22,Ukraine,Midfielder,LNZ Cherkasy,Ukraine Premier League,Ukraine,2026/2027,6,...,1,0.35,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
10478,Yurii Klymchuk,1997/05/05,29,Ukraine,Forward,Kolos Kovalivka,Ukraine Premier League,Ukraine,2026/2027,5,...,3,0.89,0.0,0.0,3.0,0.89,0.0,0.0,0.0,0.0
10479,Yurii Kokodynyak,2007/07/14,19,Ukraine,Defender,Karpaty,Ukraine Premier League,Ukraine,2026/2027,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10480,Yurii Potimkov,2002/08/01,24,Ukraine,Defender,Kudrivka,Ukraine Premier League,Ukraine,2026/2027,2,...,3,1.50,0.0,0.0,3.0,1.50,0.0,0.0,0.0,0.0
10481,Zurab Rukhadze,2003/07/30,23,Georgia,Defender,Kolos Kovalivka,Ukraine Premier League,Ukraine,2026/2027,2,...,2,1.07,0.0,0.0,2.0,1.06,0.0,0.0,0.0,0.0

In [9]:
# přejmenování sloupců

df.columns = ['player_name', 'birthday', 'age', 'nationality', 'position', 'Current Club', 'league_name', 'league_nationality', 'season', 'appearances', 'minutes_played', 'goals', 'goals_per_90', 
        'min_per_goal', 'xg', 'xg_per_90', 'npxg', 'npxg_per_90', 'assists', 'assists_per_90', 'min_per_assist', 
        'xa', 'xa_per_90', 'goals_involved_per_90', 'avg_rating_', 'rank_in_league_top_defenders', 'rank_in_league_top_midfielders', 'rank_in_league_top_attackers', 
        'shots', 'shots_per_90', 'shots_on_target', 'shots_on_target_per_90', 'shot_accuraccy_percentage', 'passes', 'passes_per_90', 
        'passes_completed', 'passes_completed_per_90', 'pass_completion_rate', 'key_passes', 'key_passes_per_90', 'crosses', 
        'crosses_per_90', 'accurate_crosses', 'accurate_crosses_per_90', 'cross_completion_rate', 'dribbles', 'dribbles_per_90', 
        'dribbles_successful', 'dribbles_successful_per_90', 'dribbled_past', 'dribbled_past_per_90', 'tackles', 'tackles_per_90', 
        'interceptions', 'interceptions_per_90', 'blocks', 'blocks_per_90', 'clearances', 'clearances_per_90', 'aerial_duels_won', 
        'aerial_duels_won_per_90', 'duels', 'duels_per_90', 'duels_won', 'duels_won_per_90', 'clean_sheets', 'conceded_goals', 
        'conceded_per_90', 'saves', 'saves_per_90', 'shots_faced', 'shots_faced_per_90', 'save_percentage', 'punches', 'punches_per_90', 'pens_saved'
]

In [10]:
# smazání Nan řádků ve full_name

df = df.dropna(subset=['player_name'])
df

,player_name,birthday,age,nationality,position,Current Club,league_name,league_nationality,season,appearances,...,conceded_goals,conceded_per_90,saves,saves_per_90,shots_faced,shots_faced_per_90,save_percentage,punches,punches_per_90,pens_saved
1,Aaron Sky Schwarz,2004/03/20,22,Austria,Forward,Wolfsberger AC,Austrian Bundesliga,Austria,2026/2027,5,...,3,0.99,0.0,0.0,3.0,0.99,0.0,0.0,0.0,0.0
2,Abdoulaye Kanté,2005/05/15,21,Ivory Coast,Forward,Austria Wien,Austrian Bundesliga,Austria,2026/2027,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abobkar Bari,2000/07/02,26,Gambia,Midfielder,Salzburg,Austrian Bundesliga,Austria,2026/2027,6,...,4,0.76,0.0,0.0,4.0,0.76,0.0,0.0,0.0,0.0
4,Aboubacar Sidiki Camara,2006/09/30,19,Burkina Faso,Forward,Salzburg,Austrian Bundesliga,Austria,2026/2027,4,...,1,0.56,0.0,0.0,1.0,0.56,0.0,0.0,0.0,0.0
5,Ademola Ola-Adebomi,2003/09/03,23,England,Forward,Wattens,Austrian Bundesliga,Austria,2026/2027,2,...,1,3.46,0.0,0.0,1.0,3.46,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10477,Yevhenii Pastukh,2004/03/19,22,Ukraine,Midfielder,LNZ Cherkasy,Ukraine Premier League,Ukraine,2026/2027,6,...,1,0.35,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
10478,Yurii Klymchuk,1997/05/05,29,Ukraine,Forward,Kolos Kovalivka,Ukraine Premier League,Ukraine,2026/2027,5,...,3,0.89,0.0,0.0,3.0,0.89,0.0,0.0,0.0,0.0
10479,Yurii Kokodynyak,2007/07/14,19,Ukraine,Defender,Karpaty,Ukraine Premier League,Ukraine,2026/2027,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10480,Yurii Potimkov,2002/08/01,24,Ukraine,Defender,Kudrivka,Ukraine Premier League,Ukraine,2026/2027,2,...,3,1.50,0.0,0.0,3.0,1.50,0.0,0.0,0.0,0.0
10481,Zurab Rukhadze,2003/07/30,23,Georgia,Defender,Kolos Kovalivka,Ukraine Premier League,Ukraine,2026/2027,2,...,2,1.07,0.0,0.0,2.0,1.06,0.0,0.0,0.0,0.0

In [11]:
df.to_excel('db.xlsx')