In [1]:
import pandas as pd

In [2]:
# spojení excelů 

aus1 = pd.read_csv('datasets/austria-bundesliga-players-2025-to-2026-stats.csv')
aus2 = pd.read_csv('datasets/austria-2-liga-players-2025-to-2026-stats.csv')
bos1 = pd.read_csv('datasets/bosnia-and-herzegovina-premier-league-of-bosnia-players-2025-to-2026-stats.csv')
bul1 = pd.read_csv('datasets/bulgaria-first-league-players-2025-to-2026-stats.csv')
cro1 = pd.read_csv('datasets/croatia-prva-hnl-players-2025-to-2026-stats.csv')
cro2 = pd.read_csv('datasets/croatia-druga-hnl-players-2025-to-2026-stats.csv')
cze1 = pd.read_csv('datasets/czech-republic-first-league-players-2025-to-2026-stats.csv')
den1 = pd.read_csv('datasets/denmark-superliga-players-2025-to-2026-stats.csv')
den2 = pd.read_csv('datasets/denmark-1st-division-players-2025-to-2026-stats.csv')
est1 = pd.read_csv('datasets/estonia-meistriliiga-players-2026-to-2026-stats.csv')
fin1 = pd.read_csv('datasets/finland-veikkausliiga-players-2026-to-2026-stats.csv')
pol1 = pd.read_csv('datasets/poland-ekstraklasa-players-2025-to-2026-stats.csv')
pol2 = pd.read_csv('datasets/poland-1-liga-players-2025-to-2026-stats.csv')
hun1 = pd.read_csv('datasets/hungary-nb-i-players-2025-to-2026-stats.csv')
lat1 = pd.read_csv('datasets/latvia-virsliga-players-2026-to-2026-stats.csv')
nor1 = pd.read_csv('datasets/norway-eliteserien-players-2026-to-2026-stats.csv')
nor2 = pd.read_csv('datasets/norway-first-division-players-2026-to-2026-stats.csv')
rom1 = pd.read_csv('datasets/romania-liga-i-players-2025-to-2026-stats.csv')
rom2 = pd.read_csv('datasets/romania-liga-ii-players-2025-to-2026-stats.csv')
ser1 = pd.read_csv('datasets/serbia-superliga-players-2025-to-2026-stats.csv')
ser2 = pd.read_csv('datasets/serbia-prva-liga-players-2025-to-2026-stats.csv')
svk1 = pd.read_csv('datasets/slovakia-super-liga-players-2025-to-2026-stats.csv')
slo1 = pd.read_csv('datasets/slovenia-prvaliga-players-2025-to-2026-stats.csv')
swe1 = pd.read_csv('datasets/sweden-allsvenskan-players-2026-to-2026-stats.csv')
swe2 = pd.read_csv('datasets/sweden-superettan-players-2026-to-2026-stats.csv')
ukr1 = pd.read_csv('datasets/ukraine-ukrainian-premier-league-players-2025-to-2026-stats.csv')

In [3]:
# přidání sloupce s národností ligy

aus1[['league_name', 'league_nationality']] = ['Austrian Bundesliga', 'Austria']
aus2[['league_name', 'league_nationality']] = ['Austrian 2. Liga', 'Austria']
bos1[['league_name', 'league_nationality']] = ['Bosnian WWIN Liga BiH', 'Bosnia and Herzegovina']
bul1[['league_name', 'league_nationality']] = ['Bulgarian Parva Liga', 'Bulgaria']
cro1[['league_name', 'league_nationality']] = ['Croatian HNL', 'Croatia']
cro2[['league_name', 'league_nationality']] = ['Croatian 1. NL', 'Croatia']
cze1[['league_name', 'league_nationality']] = ['Czech Chance Liga', 'Czechia']
den1[['league_name', 'league_nationality']] = ['Danish Superliga', 'Denmark']
den2[['league_name', 'league_nationality']] = ['Danish Betinia Liga', 'Denmark']
est1[['league_name', 'league_nationality']] = ['Estonian Premium Liiga', 'Estonia']
fin1[['league_name', 'league_nationality']] = ['Finland Veikkausliiga', 'Finland']
pol1[['league_name', 'league_nationality']] = ['Polish Ekstraklasa', 'Poland']
pol2[['league_name', 'league_nationality']] = ['Polish Betclic 1. Liga', 'Poland']
hun1[['league_name', 'league_nationality']] = ['Hungarian Fizz Liga', 'Hungary']
lat1[['league_name', 'league_nationality']] = ['Latvian Virsliga', 'Latvia']
nor1[['league_name', 'league_nationality']] = ['Eliteserien', 'Norway']
nor2[['league_name', 'league_nationality']] = ['Norway First Division', 'Norway']
rom1[['league_name', 'league_nationality']] = ['Romanian SuperLiga', 'Romania']
rom2[['league_name', 'league_nationality']] = ['Romanian Liga II', 'Romania']
ser1[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Superliga', 'Serbia']
ser2[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Prva Liga', 'Serbia']
svk1[['league_name', 'league_nationality']] = ['Slovak Niké Liga', 'Slovakia']
slo1[['league_name', 'league_nationality']] = ['Slovenian PrvaLiga', 'Slovenia']
swe1[['league_name', 'league_nationality']] = ['Sweden Allsvenskan', 'Sweden']
swe2[['league_name', 'league_nationality']] = ['Sweden Superettan', 'Sweden']
ukr1[['league_name', 'league_nationality']] = ['Ukraine Premier League', 'Ukraine']

In [4]:
# spojení do databáze

datasets = [aus1, aus2, bos1, bul1, cro1, cro2, cze1, den1, den2, est1, fin1, pol1, pol2, hun1, lat1, nor1, nor2, rom1, rom2, ser1, ser2, svk1, slo1, swe1, swe2, ukr1]
df = pd.concat(datasets, ignore_index=True)

In [5]:
# filtr a změna pořadí požadovaných sloupců

cols = ['full_name', 'birthday_GMT', 'age', 'nationality', 'position', 'Current Club', 'league_name', 'league_nationality', 'season', 'appearances_overall', 'minutes_played_overall', 'goals_overall', 'goals_per_90_overall', 
        'min_per_goal_overall', 'xg_total_overall', 'xg_per_90_overall', 'npxg_total_overall', 'npxg_per_90_overall', 'assists_overall', 'assists_per_90_overall', 'min_per_assist_overall', 
        'xa_total_overall', 'xa_per_90_overall', 'goals_involved_per_90_overall', 'average_rating_overall', 'rank_in_league_top_defenders', 'rank_in_league_top_midfielders', 'rank_in_league_top_attackers', 
        'shots_total_overall', 'shots_per_90_overall', 'shots_on_target_total_overall', 'shots_on_target_per_90_overall', 'shot_accuraccy_percentage_overall', 'passes_total_overall', 'passes_per_90_overall', 
        'passes_completed_total_overall', 'passes_completed_per_90_overall', 'pass_completion_rate_overall', 'key_passes_total_overall', 'key_passes_per_90_overall', 'crosses_total_overall', 
        'crosses_per_90_overall', 'accurate_crosses_total_overall', 'accurate_crosses_per_90_overall', 'cross_completion_rate_overall',  'dribbles_total_overall', 'dribbles_per_90_overall', 
        'dribbles_successful_total_overall', 'dribbles_successful_per_90_overall', 'dribbled_past_total_overall', 'dribbled_past_per_90_overall', 'tackles_total_overall', 'tackles_per_90_overall', 
        'interceptions_total_overall', 'interceptions_per_90_overall', 'blocks_total_overall', 'blocks_per_90_overall', 'clearances_total_overall', 'clearances_per_90_overall', 'aerial_duels_won_total_overall', 
        'aerial_duels_won_per_90_overall', 'duels_total_overall', 'duels_per_90_overall', 'duels_won_total_overall', 'duels_won_per_90_overall', 'clean_sheets_overall', 'conceded_overall', 
        'conceded_per_90_overall', 'saves_total_overall', 'saves_per_90_overall', 'shots_faced_total_overall', 'shots_faced_per_90_overall', 'save_percentage_overall', 'punches_total_overall', 
        'punches_per_90_overall', 'pens_saved_total_overall'
]

df = df[cols]
df

,full_name,birthday_GMT,age,nationality,position,Current Club,league_name,league_nationality,season,appearances_overall,...,conceded_overall,conceded_per_90_overall,saves_total_overall,saves_per_90_overall,shots_faced_total_overall,shots_faced_per_90_overall,save_percentage_overall,punches_total_overall,punches_per_90_overall,pens_saved_total_overall
0,NaN,1989/07/08,36,China,Midfielder,LASK Linz,Austrian Bundesliga,Austria,2025/2026,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Kantu00e9,2005/05/15,21,Ivory Coast,Forward,Austria Wien,Austrian Bundesliga,Austria,2025/2026,2,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
2,Abobkar Bari,2000/07/02,25,Gambia,Midfielder,Austria Wien,Austrian Bundesliga,Austria,2025/2026,28,...,43,1.60,0.0,0.00,39.0,1.45,0.00,0.0,0.00,0.0
3,Adam Daghim,2005/09/28,20,Denmark,Forward,Salzburg,Austrian Bundesliga,Austria,2025/2026,3,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
4,Adam Stejskal,2002/08/23,23,Czech Republic,Goalkeeper,Wattens,Austrian Bundesliga,Austria,2025/2026,31,...,50,1.61,67.0,2.16,118.0,3.81,56.78,18.0,0.58,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11526,Yurii-Volodymyr Gereta,2004/01/30,22,Ukraine,Goalkeeper,Rukh Vynnyky,Ukraine Premier League,Ukraine,2025/2026,25,...,40,1.60,16.0,0.64,57.0,2.28,28.07,0.0,0.00,0.0
11527,Zakhariy Zakharkiv,2008/02/17,18,Ukraine,Forward,Kolos Kovalivka,Ukraine Premier League,Ukraine,2025/2026,3,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
11528,Žan Trontelj,2000/01/21,26,Slovenia,Defender,Zorya,Ukraine Premier League,Ukraine,2025/2026,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11529,Zurab Rukhadze,2003/07/30,22,Georgia,Defender,Kolos Kovalivka,Ukraine Premier League,Ukraine,2025/2026,5,...,3,0.95,0.0,0.00,4.0,1.27,0.00,0.0,0.00,0.0
11530,Іvan Golovkіn,2000/05/24,26,Ukraine,Midfielder,Zorya,Ukraine Premier League,Ukraine,2025/2026,1,...,0,0.00,0.0,0.00,1.0,45.00,0.00,0.0,0.00,0.0

In [6]:
# přejmenování sloupců

df.columns = ['player_name', 'birthday', 'age', 'nationality', 'position', 'Current Club', 'league_name', 'league_nationality', 'season', 'appearances', 'minutes_played', 'goals', 'goals_per_90', 
        'min_per_goal', 'xg', 'xg_per_90', 'npxg', 'npxg_per_90', 'assists', 'assists_per_90', 'min_per_assist', 
        'xa', 'xa_per_90', 'goals_involved_per_90', 'avg_rating_', 'rank_in_league_top_defenders', 'rank_in_league_top_midfielders', 'rank_in_league_top_attackers', 
        'shots', 'shots_per_90', 'shots_on_target', 'shots_on_target_per_90', 'shot_accuraccy_percentage', 'passes', 'passes_per_90', 
        'passes_completed', 'passes_completed_per_90', 'pass_completion_rate', 'key_passes', 'key_passes_per_90', 'crosses', 
        'crosses_per_90', 'accurate_crosses', 'accurate_crosses_per_90', 'cross_completion_rate', 'dribbles', 'dribbles_per_90', 
        'dribbles_successful', 'dribbles_successful_per_90', 'dribbled_past', 'dribbled_past_per_90', 'tackles', 'tackles_per_90', 
        'interceptions', 'interceptions_per_90', 'blocks', 'blocks_per_90', 'clearances', 'clearances_per_90', 'aerial_duels_won', 
        'aerial_duels_won_per_90', 'duels', 'duels_per_90', 'duels_won', 'duels_won_per_90', 'clean_sheets', 'conceded_goals', 
        'conceded_per_90', 'saves', 'saves_per_90', 'shots_faced', 'shots_faced_per_90', 'save_percentage', 'punches', 'punches_per_90', 'pens_saved'
]

In [7]:
# smazání Nan řádků ve full_name

df = df.dropna(subset=['player_name'])
df

,player_name,birthday,age,nationality,position,Current Club,league_name,league_nationality,season,appearances,...,conceded_goals,conceded_per_90,saves,saves_per_90,shots_faced,shots_faced_per_90,save_percentage,punches,punches_per_90,pens_saved
1,Abdoulaye Kantu00e9,2005/05/15,21,Ivory Coast,Forward,Austria Wien,Austrian Bundesliga,Austria,2025/2026,2,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
2,Abobkar Bari,2000/07/02,25,Gambia,Midfielder,Austria Wien,Austrian Bundesliga,Austria,2025/2026,28,...,43,1.60,0.0,0.00,39.0,1.45,0.00,0.0,0.00,0.0
3,Adam Daghim,2005/09/28,20,Denmark,Forward,Salzburg,Austrian Bundesliga,Austria,2025/2026,3,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
4,Adam Stejskal,2002/08/23,23,Czech Republic,Goalkeeper,Wattens,Austrian Bundesliga,Austria,2025/2026,31,...,50,1.61,67.0,2.16,118.0,3.81,56.78,18.0,0.58,1.0
5,Adama Drame,2005/01/05,21,Ivory Coast,Defender,Wolfsberger AC,Austrian Bundesliga,Austria,2025/2026,2,...,1,3.21,0.0,0.00,1.0,3.21,0.00,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11526,Yurii-Volodymyr Gereta,2004/01/30,22,Ukraine,Goalkeeper,Rukh Vynnyky,Ukraine Premier League,Ukraine,2025/2026,25,...,40,1.60,16.0,0.64,57.0,2.28,28.07,0.0,0.00,0.0
11527,Zakhariy Zakharkiv,2008/02/17,18,Ukraine,Forward,Kolos Kovalivka,Ukraine Premier League,Ukraine,2025/2026,3,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
11528,Žan Trontelj,2000/01/21,26,Slovenia,Defender,Zorya,Ukraine Premier League,Ukraine,2025/2026,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11529,Zurab Rukhadze,2003/07/30,22,Georgia,Defender,Kolos Kovalivka,Ukraine Premier League,Ukraine,2025/2026,5,...,3,0.95,0.0,0.00,4.0,1.27,0.00,0.0,0.00,0.0
11530,Іvan Golovkіn,2000/05/24,26,Ukraine,Midfielder,Zorya,Ukraine Premier League,Ukraine,2025/2026,1,...,0,0.00,0.0,0.00,1.0,45.00,0.00,0.0,0.00,0.0

In [8]:
df.to_excel('db.xlsx')