In [1]:
import pandas as pd

In [2]:
# spojení excelů - chybí severské ligy, ještě nezačaly sezony

aus1 = pd.read_csv('datasets/austria-bundesliga-players-2025-to-2026-stats.csv')
aus2 = pd.read_csv('datasets/austria-2-liga-players-2025-to-2026-stats.csv')
bos1 = pd.read_csv('datasets/bosnia-and-herzegovina-premier-league-of-bosnia-players-2025-to-2026-stats.csv')
bul1 = pd.read_csv('datasets/bulgaria-first-league-players-2025-to-2026-stats.csv')
cro1 = pd.read_csv('datasets/croatia-prva-hnl-players-2025-to-2026-stats.csv')
cro2 = pd.read_csv('datasets/croatia-druga-hnl-players-2025-to-2026-stats.csv')
cze1 = pd.read_csv('datasets/czech-republic-first-league-players-2025-to-2026-stats.csv')
den1 = pd.read_csv('datasets/denmark-superliga-players-2025-to-2026-stats.csv')
den2 = pd.read_csv('datasets/denmark-1st-division-players-2025-to-2026-stats.csv')
est1 = pd.read_csv('datasets/estonia-meistriliiga-players-2026-to-2026-stats.csv')
pol1 = pd.read_csv('datasets/poland-ekstraklasa-players-2025-to-2026-stats.csv')
pol2 = pd.read_csv('datasets/poland-1-liga-players-2025-to-2026-stats.csv')
hun1 = pd.read_csv('datasets/hungary-nb-i-players-2025-to-2026-stats.csv')
lat1 = pd.read_csv('datasets/latvia-virsliga-players-2026-to-2026-stats.csv')
nor1 = pd.read_csv('datasets/norway-eliteserien-players-2026-to-2026-stats.csv')
rom1 = pd.read_csv('datasets/romania-liga-i-players-2025-to-2026-stats.csv')
rom2 = pd.read_csv('datasets/romania-liga-ii-players-2025-to-2026-stats.csv')
ser1 = pd.read_csv('datasets/serbia-superliga-players-2025-to-2026-stats.csv')
ser2 = pd.read_csv('datasets/serbia-prva-liga-players-2025-to-2026-stats.csv')
svk1 = pd.read_csv('datasets/slovakia-super-liga-players-2025-to-2026-stats.csv')
slo1 = pd.read_csv('datasets/slovenia-prvaliga-players-2025-to-2026-stats.csv')

In [3]:
# přidání sloupce s národností ligy

aus1[['league_name', 'league_nationality']] = ['Austrian Bundesliga', 'Austria']
aus2[['league_name', 'league_nationality']] = ['Austrian 2. Liga', 'Austria']
bos1[['league_name', 'league_nationality']] = ['Bosnian WWIN Liga BiH', 'Bosnia and Herzegovina']
bul1[['league_name', 'league_nationality']] = ['Bulgarian Parva Liga', 'Bulgaria']
cro1[['league_name', 'league_nationality']] = ['Croatian HNL', 'Croatia']
cro2[['league_name', 'league_nationality']] = ['Croatian 1. NL', 'Croatia']
cze1[['league_name', 'league_nationality']] = ['Czech Chance Liga', 'Czechia']
den1[['league_name', 'league_nationality']] = ['Danish Superliga', 'Denmark']
den2[['league_name', 'league_nationality']] = ['Danish Betinia Liga', 'Denmark']
est1[['league_name', 'league_nationality']] = ['Estonian Premium Liiga', 'Estonia']
pol1[['league_name', 'league_nationality']] = ['Polish Ekstraklasa', 'Poland']
pol2[['league_name', 'league_nationality']] = ['Polish Betclic 1. Liga', 'Poland']
hun1[['league_name', 'league_nationality']] = ['Hungarian Fizz Liga', 'Hungary']
lat1[['league_name', 'league_nationality']] = ['Latvian Virsliga', 'Latvia']
nor1[['league_name', 'league_nationality']] = ['Eliteserien', 'Norway']
rom1[['league_name', 'league_nationality']] = ['Romanian SuperLiga', 'Romania']
rom2[['league_name', 'league_nationality']] = ['Romanian Liga II', 'Romania']
ser1[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Superliga', 'Serbia']
ser2[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Prva Liga', 'Serbia']
svk1[['league_name', 'league_nationality']] = ['Slovak Niké Liga', 'Slovakia']
slo1[['league_name', 'league_nationality']] = ['Slovenian PrvaLiga', 'Slovenia']

C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  aus1[['league_name', 'league_nationality']] = ['Austrian Bundesliga', 'Austria']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  aus1[['league_name', 'league_nationality']] = ['Austrian Bundesliga', 'Austria']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  aus2[['league_name', 'league_nationality']] = ['Austrian 2. Liga', 'Austria']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  aus2[['league_name', 'league_nationality']] = ['Austrian 2. Liga', 'Austria']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bos1[['league_name', 'league_nationality']] = ['Bosnian WWIN Liga BiH', 'Bosnia and Herzegovina']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bos1[['league_name', 'league_nationality']] = ['Bosnian WWIN Liga BiH', 'Bosnia and Herzegovina']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bul1[['league_name', 'league_nationality']] = ['Bulgarian Parva Liga', 'Bulgaria']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bul1[['league_name', 'league_nationality']] = ['Bulgarian Parva Liga', 'Bulgaria']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cro1[['league_name', 'league_nationality']] = ['Croatian HNL', 'Croatia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cro1[['league_name', 'league_nationality']] = ['Croatian HNL', 'Croatia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cro2[['league_name', 'league_nationality']] = ['Croatian 1. NL', 'Croatia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cro2[['league_name', 'league_nationality']] = ['Croatian 1. NL', 'Croatia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cze1[['league_name', 'league_nationality']] = ['Czech Chance Liga', 'Czechia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cze1[['league_name', 'league_nationality']] = ['Czech Chance Liga', 'Czechia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  den1[['league_name', 'league_nationality']] = ['Danish Superliga', 'Denmark']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  den1[['league_name', 'league_nationality']] = ['Danish Superliga', 'Denmark']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  den2[['league_name', 'league_nationality']] = ['Danish Betinia Liga', 'Denmark']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  den2[['league_name', 'league_nationality']] = ['Danish Betinia Liga', 'Denmark']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  est1[['league_name', 'league_nationality']] = ['Estonian Premium Liiga', 'Estonia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  est1[['league_name', 'league_nationality']] = ['Estonian Premium Liiga', 'Estonia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pol1[['league_name', 'league_nationality']] = ['Polish Ekstraklasa', 'Poland']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pol1[['league_name', 'league_nationality']] = ['Polish Ekstraklasa', 'Poland']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pol2[['league_name', 'league_nationality']] = ['Polish Betclic 1. Liga', 'Poland']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pol2[['league_name', 'league_nationality']] = ['Polish Betclic 1. Liga', 'Poland']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  hun1[['league_name', 'league_nationality']] = ['Hungarian Fizz Liga', 'Hungary']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  hun1[['league_name', 'league_nationality']] = ['Hungarian Fizz Liga', 'Hungary']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  lat1[['league_name', 'league_nationality']] = ['Latvian Virsliga', 'Latvia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  lat1[['league_name', 'league_nationality']] = ['Latvian Virsliga', 'Latvia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nor1[['league_name', 'league_nationality']] = ['Eliteserien', 'Norway']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nor1[['league_name', 'league_nationality']] = ['Eliteserien', 'Norway']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rom1[['league_name', 'league_nationality']] = ['Romanian SuperLiga', 'Romania']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rom1[['league_name', 'league_nationality']] = ['Romanian SuperLiga', 'Romania']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rom2[['league_name', 'league_nationality']] = ['Romanian Liga II', 'Romania']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rom2[['league_name', 'league_nationality']] = ['Romanian Liga II', 'Romania']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ser1[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Superliga', 'Serbia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ser1[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Superliga', 'Serbia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ser2[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Prva Liga', 'Serbia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ser2[['league_name', 'league_nationality']] = ['Serbian Mozzart Bet Prva Liga', 'Serbia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  svk1[['league_name', 'league_nationality']] = ['Slovak Niké Liga', 'Slovakia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  svk1[['league_name', 'league_nationality']] = ['Slovak Niké Liga', 'Slovakia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  slo1[['league_name', 'league_nationality']] = ['Slovenian PrvaLiga', 'Slovenia']
C:\Users\petrm\AppData\Local\Temp\ipykernel_6360\2079861560.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  slo1[['league_name', 'league_nationality']] = ['Slovenian PrvaLiga', 'Slovenia']

In [4]:
# spojení do databáze

datasets = [aus1, aus2, bos1, bul1, cro1, cro2, cze1, den1, den2, est1, pol1, pol2, hun1, lat1, nor1, rom1, rom2, ser1, ser2, svk1, slo1]
df = pd.concat(datasets, ignore_index=True)

In [5]:
# filtr a změna pořadí požadovaných sloupců

cols = ['full_name', 'birthday_GMT', 'age', 'nationality', 'position', 'Current Club', 'league_name', 'league_nationality', 'season', 'appearances_overall', 'minutes_played_overall', 'goals_overall', 'goals_per_90_overall', 
        'min_per_goal_overall', 'xg_total_overall', 'xg_per_90_overall', 'npxg_total_overall', 'npxg_per_90_overall', 'assists_overall', 'assists_per_90_overall', 'min_per_assist_overall', 
        'xa_total_overall', 'xa_per_90_overall', 'goals_involved_per_90_overall', 'average_rating_overall', 'rank_in_league_top_defenders', 'rank_in_league_top_midfielders', 'rank_in_league_top_attackers', 
        'shots_total_overall', 'shots_per_90_overall', 'shots_on_target_total_overall', 'shots_on_target_per_90_overall', 'shot_accuraccy_percentage_overall', 'passes_total_overall', 'passes_per_90_overall', 
        'passes_completed_total_overall', 'passes_completed_per_90_overall', 'pass_completion_rate_overall', 'key_passes_total_overall', 'key_passes_per_90_overall', 'crosses_total_overall', 
        'crosses_per_90_overall', 'accurate_crosses_total_overall', 'accurate_crosses_per_90_overall', 'cross_completion_rate_overall',  'dribbles_total_overall', 'dribbles_per_90_overall', 
        'dribbles_successful_total_overall', 'dribbles_successful_per_90_overall', 'dribbled_past_total_overall', 'dribbled_past_per_90_overall', 'tackles_total_overall', 'tackles_per_90_overall', 
        'interceptions_total_overall', 'interceptions_per_90_overall', 'blocks_total_overall', 'blocks_per_90_overall', 'clearances_total_overall', 'clearances_per_90_overall', 'aerial_duels_won_total_overall', 
        'aerial_duels_won_per_90_overall', 'duels_total_overall', 'duels_per_90_overall', 'duels_won_total_overall', 'duels_won_per_90_overall', 'clean_sheets_overall', 'conceded_overall', 
        'conceded_per_90_overall', 'saves_total_overall', 'saves_per_90_overall', 'shots_faced_total_overall', 'shots_faced_per_90_overall', 'save_percentage_overall', 'punches_total_overall', 
        'punches_per_90_overall', 'pens_saved_total_overall'
]

df = df[cols]
df

,full_name,birthday_GMT,age,nationality,position,Current Club,league_name,league_nationality,season,appearances_overall,...,conceded_overall,conceded_per_90_overall,saves_total_overall,saves_per_90_overall,shots_faced_total_overall,shots_faced_per_90_overall,save_percentage_overall,punches_total_overall,punches_per_90_overall,pens_saved_total_overall
0,NaN,1989/07/08,36,NaN,Midfielder,Rheindorf Altach,Austrian Bundesliga,Austria,2025/2026,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Kantu00e9,2005/05/15,20,Ivory Coast,Midfielder,Austria Wien,Austrian Bundesliga,Austria,2025/2026,1,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
2,Abobkar Bari,2000/07/02,25,Gambia,Midfielder,Austria Wien,Austrian Bundesliga,Austria,2025/2026,22,...,32,1.52,0.0,0.00,28.0,1.33,0.00,0.0,0.00,0.0
3,Adam Daghim,2005/09/28,20,Denmark,Midfielder,Salzburg,Austrian Bundesliga,Austria,2025/2026,3,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
4,Adam Stejskal,2002/08/23,23,Czech Republic,Goalkeeper,Wattens,Austrian Bundesliga,Austria,2025/2026,22,...,30,1.36,46.0,2.09,77.0,3.50,59.74,15.0,0.68,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,Žan Žabkar,2005/03/30,20,Slovenia,Midfielder,Koper,Slovenian PrvaLiga,Slovenia,2025/2026,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8365,Žan Žaler,2002/08/30,23,Slovenia,Midfielder,Radomlje,Slovenian PrvaLiga,Slovenia,2025/2026,18,...,20,1.57,0.0,0.00,23.0,1.80,0.00,0.0,0.00,0.0
8366,Žiga Pečjak,NaN,56,Slovenia,Forward,Olimpija,Slovenian PrvaLiga,Slovenia,2025/2026,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8367,Žiga Repas,2001/05/29,24,Slovenia,Midfielder,Maribor,Slovenian PrvaLiga,Slovenia,2025/2026,8,...,3,0.97,0.0,0.00,4.0,1.27,0.00,0.0,0.00,0.0
8368,Łukasz Bejger,2002/01/11,24,Poland,Defender,Celje,Slovenian PrvaLiga,Slovenia,2025/2026,19,...,15,0.95,0.0,0.00,18.0,1.15,0.00,0.0,0.00,0.0

In [6]:
# přejmenování sloupců

df.columns = ['player_name', 'birthday', 'age', 'nationality', 'position', 'Current Club', 'league_name', 'league_nationality', 'season', 'appearances', 'minutes_played', 'goals', 'goals_per_90', 
        'min_per_goal', 'xg', 'xg_per_90', 'npxg', 'npxg_per_90', 'assists', 'assists_per_90', 'min_per_assist', 
        'xa', 'xa_per_90', 'goals_involved_per_90', 'avg_rating_', 'rank_in_league_top_defenders', 'rank_in_league_top_midfielders', 'rank_in_league_top_attackers', 
        'shots', 'shots_per_90', 'shots_on_target', 'shots_on_target_per_90', 'shot_accuraccy_percentage', 'passes', 'passes_per_90', 
        'passes_completed', 'passes_completed_per_90', 'pass_completion_rate', 'key_passes', 'key_passes_per_90', 'crosses', 
        'crosses_per_90', 'accurate_crosses', 'accurate_crosses_per_90', 'cross_completion_rate', 'dribbles', 'dribbles_per_90', 
        'dribbles_successful', 'dribbles_successful_per_90', 'dribbled_past', 'dribbled_past_per_90', 'tackles', 'tackles_per_90', 
        'interceptions', 'interceptions_per_90', 'blocks', 'blocks_per_90', 'clearances', 'clearances_per_90', 'aerial_duels_won', 
        'aerial_duels_won_per_90', 'duels', 'duels_per_90', 'duels_won', 'duels_won_per_90', 'clean_sheets', 'conceded_goals', 
        'conceded_per_90', 'saves', 'saves_per_90', 'shots_faced', 'shots_faced_per_90', 'save_percentage', 'punches', 'punches_per_90', 'pens_saved'
]

In [7]:
# smazání Nan řádků ve full_name

df = df.dropna(subset=['player_name'])
df

,player_name,birthday,age,nationality,position,Current Club,league_name,league_nationality,season,appearances,...,conceded_goals,conceded_per_90,saves,saves_per_90,shots_faced,shots_faced_per_90,save_percentage,punches,punches_per_90,pens_saved
1,Abdoulaye Kantu00e9,2005/05/15,20,Ivory Coast,Midfielder,Austria Wien,Austrian Bundesliga,Austria,2025/2026,1,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
2,Abobkar Bari,2000/07/02,25,Gambia,Midfielder,Austria Wien,Austrian Bundesliga,Austria,2025/2026,22,...,32,1.52,0.0,0.00,28.0,1.33,0.00,0.0,0.00,0.0
3,Adam Daghim,2005/09/28,20,Denmark,Midfielder,Salzburg,Austrian Bundesliga,Austria,2025/2026,3,...,0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0
4,Adam Stejskal,2002/08/23,23,Czech Republic,Goalkeeper,Wattens,Austrian Bundesliga,Austria,2025/2026,22,...,30,1.36,46.0,2.09,77.0,3.50,59.74,15.0,0.68,1.0
5,Adama Drame,2005/01/05,21,Ivory Coast,Midfielder,Wolfsberger AC,Austrian Bundesliga,Austria,2025/2026,2,...,1,3.21,0.0,0.00,1.0,3.21,0.00,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,Žan Žabkar,2005/03/30,20,Slovenia,Midfielder,Koper,Slovenian PrvaLiga,Slovenia,2025/2026,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8365,Žan Žaler,2002/08/30,23,Slovenia,Midfielder,Radomlje,Slovenian PrvaLiga,Slovenia,2025/2026,18,...,20,1.57,0.0,0.00,23.0,1.80,0.00,0.0,0.00,0.0
8366,Žiga Pečjak,NaN,56,Slovenia,Forward,Olimpija,Slovenian PrvaLiga,Slovenia,2025/2026,0,...,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8367,Žiga Repas,2001/05/29,24,Slovenia,Midfielder,Maribor,Slovenian PrvaLiga,Slovenia,2025/2026,8,...,3,0.97,0.0,0.00,4.0,1.27,0.00,0.0,0.00,0.0
8368,Łukasz Bejger,2002/01/11,24,Poland,Defender,Celje,Slovenian PrvaLiga,Slovenia,2025/2026,19,...,15,0.95,0.0,0.00,18.0,1.15,0.00,0.0,0.00,0.0

In [8]:
df.to_excel('db.xlsx')